### ISSUE TITLE
session data not deleted

### ISSUE THREAD

**Issue by tyagirajat200** [shawn-dsilva/mern-login-signup-component#2]
when I test routes on postman all were working fine and session also deleted from mongo i.e al working fine . 
But  when i send request from react there are various issues
1- when logged in seesion created but when logged out session not deleted from mongodb.
2- for authechecker it always return error i.e false if i already logged in .i think  seesion is not there .
please help to remove this 
also can u please make part 2 of this post as i saw on your website

**Comment by tyagirajat200** [comment]
i recently found that cookies are not created in browser thats why all above errors are came please tell

**Comment by shawn-dsilva** [comment]
The line `axios.defaults.baseURL = "http://localhost:5000";` in `client/src/actions/authActions.js is the culprit causing this, removing or commenting out this line fixes the problem of the cookie not being set.

Axios will obtain the baseURL for the backend server if testing locally by checking the value of `proxy:` in the `package.json` file, there is no need to specify it using `axios.defaults.baseURL = "http://localhost:5000";` , this was a mistake by my part, thanks for bringing it to my attention.

If you are hosting this project on the wider internet, under your own domain, you do need to specify the domain using `axios.defaults.baseURL` however.

Also yes, i will make part two of the post, i see there is great demand for it :-)

**Comment by shawn-dsilva** [comment]
"Cookies not being set when developing locally " Issue is fixed with the latest commit number `2477182b58055a3952c1a981854ef815ef2469ab`, i am closing this issue now

**Comment by tyagirajat200** [comment]
thank you very much for your response now working fine. I m very happy now
